version: '3'

services:
  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_DATABASE=grafana"
      - "MYSQL_USER=monitor"
      - "MYSQL_PASSWORD="
    volumes:
      - /data/mysql/grafana:/var/lib/mysql
    networks:
      - public

  influx:
    image: influxdb:1.7.1
    container_name: influxdb
    depends_on:
      - mariadb
    ports:
      - "8086:8086"
      - "127.0.0.1:8083:8083"
    environment:
      - "INFLUXDB_REPORTING_DISABLED=true"
      - "INFLUXDB_DB=influx"
      - "INFLUXDB_ADMIN_USER="
      - "INFLUXDB_ADMIN_PASSWORD="
      - "INFLUXDB_WRITE_USER="
      - "INFLUXDB_WRITE_USER_PASSWORD="
      - "INFLUXDB_DATA_QUERY_LOG_ENABLED=false"
    volumes:
      - /data/influxdb/data:/var/lib/influxdb
    networks:
      - public

  grafana:
    links:
     - influx
     - mariadb:db
    image: grafana/grafana:5.3.4
    container_name: grafana
    depends_on:
      - mariadb
    ports:
      - "3000:3000"
    environment:
      - "GF_SERVER_DOMAIN="
      - "GF_SERVER_ROOT_URL="
      - "GF_SECURITY_ADMIN_PASSWORD="
      - "GF_DATABASE_TYPE=mysql"
      - "GF_DATABASE_SSL_MODE=verify-full"
      - "GF_DATABASE_NAME=grafana"
      - "GF_DATABASE_USER=monitor"
      - "GF_DATABASE_HOST=db"
      - "GF_DATABASE_PASSWORD="
      - "GF_ANALYTICS_REPORTING_ENABLED=false"
      - "GF_PATHS_PLUGINS=/plugins"
    volumes:
      - /data/grafana/plugins:/plugins
    networks:
      - public

networks:
  public:
    external: true



